source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'loki_Example', :exclusive => true do
  pod "Loki", :path => "../"
end

target 'loki_Tests', :exclusive => true do
  pod "Loki", :path => "../"

  
end
